import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = resolve(root, "src/main.js");

const generated = `/* This file is generated by scripts/generate-entry.mjs. */
/* The application is now a real ES module graph; no source is concatenated here. */
import "../assets/css/base.css";
import "../assets/css/animations.css";
import "../assets/css/components.css";
import { initializeUI } from "../assets/js/ui.js";
import "../assets/js/lifecycle.js";

initializeUI();
`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, "utf8");
console.log(`Generated ES module entry ${output}.`);
