import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const indexHtml = await readFile(resolve(root, "index.html"), "utf8");

const moduleFiles = [
  "synth.js",
  "data.js",
  "state.js",
  "lifecycle.js",
  "drawing.js",
  "stickers.js",
  "animations.js",
  "audio-controls.js",
  "utilities-gallery.js",
  "settings.js",
  "export-particles.js",
  "voice-duo.js",
];

const moduleSources = await Promise.all(
  moduleFiles.map(async (file) => {
    const source = await readFile(resolve(root, "assets/js", file), "utf8");
    return `\n/* ===== ${file} ===== */\n${source.trim()}\n`;
  }),
);

// The existing markup uses inline callbacks. Keep that public contract while
// the implementation itself is bundled as one Vite module.
const inlineNames = [
  ...indexHtml.matchAll(/(?:onclick|oninput)\s*=\s*"([A-Za-z_$][\w$]*)\s*\(/g),
].map((match) => match[1]);
const publicNames = [...new Set(inlineNames)].sort();

const bridge = `\n\n/* Public bridge for the legacy inline HTML callbacks. */\nObject.assign(globalThis, {\n${publicNames
  .map((name) => `  ${name},`)
  .join("\n")}\n});\n`;

const cssImports = [
  'import "../../assets/css/base.css";',
  'import "../../assets/css/animations.css";',
  'import "../../assets/css/components.css";',
].join("\n");

const generated = `/* This file is generated by scripts/generate-entry.mjs. Do not edit it directly. */\n${cssImports}\n${moduleSources.join("\n")}${bridge}`;
const output = resolve(root, "src/generated/app.js");
await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, "utf8");
console.log(`Generated ${output} from ${moduleFiles.length} source modules.`);
