import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const indexHtml = await readFile(resolve(root, "index.html"), "utf8");
const sourceRoot = "../assets/js";

const modules = [
  { file: "state.js", names: ["state"] },
  { file: "synth.js", names: ["KidSynth", "synth"] },
  { file: "data.js", names: ["stickersData", "stampTemplates", "superheroes", "colors", "positiveQuotes", "aliveMessages"] },
  { file: "lifecycle.js", names: ["setupCanvasDimensions", "handleWindowResize"] },
  {
    file: "drawing.js",
    names: [
      "renderColors", "selectColor", "selectEraser", "startDrawing", "draw", "drawSpray", "stopDrawing",
      "selectFillTool", "performFloodFill", "toggleMirror", "toggleStampsModal", "renderStampsGallery",
      "selectStamp", "placeStamp", "selectCanvasBg", "drawCanvasBackground", "clearCanvas", "saveState",
      "undo", "redo", "updateUndoRedoButtons", "restoreCanvas", "selectSpray", "selectCustomColor",
      "renderMobileColors", "toggleMobileDrawer", "handleBackdropClick", "downloadDrawingPNG",
    ],
  },
  { file: "stickers.js", names: ["renderStickers", "filterStickers", "addStickerToCanvas", "deselectAllStickers", "setupStickerPointerData"] },
  { file: "animations.js", names: ["stopAllAnimations", "triggerAnimation", "toggleGiveLife", "cycleSpeechMessages", "toggleTheme"] },
  { file: "audio-controls.js", names: ["toggleMusic"] },
  {
    file: "utilities-gallery.js",
    names: [
      "resetApp", "toggleHeroModal", "renderHeroesGallery", "filterTemplates", "loadSuperhero",
      "getSavedDrawings", "saveDrawingToGallery", "deleteDrawingFromGallery", "renderGalleryGrid",
      "loadDrawingFromGallery", "saveCurrentDrawingToGallery", "toggleGalleryModal", "celebrateName",
      "getFriends", "saveFriends", "addFriend", "removeFriend", "resetFriends", "addSampleFriends",
      "renderFriendBadges", "renderFriendList", "toggleFriendsModal",
    ],
  },
  { file: "settings.js", names: ["animationSpeed", "setAnimationSpeed", "setTemplateOpacity", "toggleHelpModal", "animalReact", "showEncouragement", "triggerConfetti"] },
  { file: "export-particles.js", names: ["saveDrawing", "initParticles", "resizeParticlesCanvas", "spawnParticles", "updateParticles", "drawStar"] },
  { file: "voice-duo.js", names: ["speakArabic", "toggleSplitMode"] },
];

const inlineNames = [
  ...indexHtml.matchAll(/(?:onclick|oninput)\s*=\s*"([A-Za-z_$][\w$]*)\s*\(/g),
].map((match) => match[1]);

const exportedNames = [...new Set(modules.flatMap(({ names }) => names))];
const publicNames = [...new Set([...exportedNames, ...inlineNames])].sort();
const imports = modules
  .map(({ file, names }) => `import { ${names.join(", ")} } from "${sourceRoot}/${file}";`)
  .join("\n");
const globals = publicNames.map((name) => `  ${name},`).join("\n");
const cssImports = [
  'import "../assets/css/base.css";',
  'import "../assets/css/animations.css";',
  'import "../assets/css/components.css";',
].join("\n");

const generated = `/* This file is generated by scripts/generate-entry.mjs. */
/* It is an ES module entry: source files stay separate and Vite builds the graph. */
${cssImports}
${imports}

// Keep the legacy inline HTML callbacks working while the application migrates
// to addEventListener-based UI wiring.
Object.assign(globalThis, {
${globals}
});
`;

const output = resolve(root, "src/main.js");
await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, "utf8");
console.log(`Generated ES module entry ${output} from ${modules.length} source modules.`);
