/* This file is generated by scripts/generate-entry.mjs. */
/* It is an ES module entry: source files stay separate and Vite builds the graph. */
import "../assets/css/base.css";
import "../assets/css/animations.css";
import "../assets/css/components.css";
import { state } from "../assets/js/state.js";
import { KidSynth, synth } from "../assets/js/synth.js";
import { stickersData, stampTemplates, superheroes, colors, positiveQuotes, aliveMessages } from "../assets/js/data.js";
import { setupCanvasDimensions, handleWindowResize } from "../assets/js/lifecycle.js";
import { renderColors, selectColor, selectEraser, startDrawing, draw, drawSpray, stopDrawing, selectFillTool, performFloodFill, toggleMirror, toggleStampsModal, renderStampsGallery, selectStamp, placeStamp, selectCanvasBg, drawCanvasBackground, clearCanvas, saveState, undo, redo, updateUndoRedoButtons, restoreCanvas, selectSpray, selectCustomColor, renderMobileColors, toggleMobileDrawer, handleBackdropClick, downloadDrawingPNG } from "../assets/js/drawing.js";
import { renderStickers, filterStickers, addStickerToCanvas, deselectAllStickers, setupStickerPointerData } from "../assets/js/stickers.js";
import { stopAllAnimations, triggerAnimation, toggleGiveLife, cycleSpeechMessages, toggleTheme } from "../assets/js/animations.js";
import { toggleMusic } from "../assets/js/audio-controls.js";
import { resetApp, toggleHeroModal, renderHeroesGallery, filterTemplates, loadSuperhero, getSavedDrawings, saveDrawingToGallery, deleteDrawingFromGallery, renderGalleryGrid, loadDrawingFromGallery, saveCurrentDrawingToGallery, toggleGalleryModal, celebrateName, getFriends, saveFriends, addFriend, removeFriend, resetFriends, addSampleFriends, renderFriendBadges, renderFriendList, toggleFriendsModal } from "../assets/js/utilities-gallery.js";
import { animationSpeed, setAnimationSpeed, setTemplateOpacity, toggleHelpModal, animalReact, showEncouragement, triggerConfetti } from "../assets/js/settings.js";
import { saveDrawing, initParticles, resizeParticlesCanvas, spawnParticles, updateParticles, drawStar } from "../assets/js/export-particles.js";
import { speakArabic, toggleSplitMode } from "../assets/js/voice-duo.js";

// Keep the legacy inline HTML callbacks working while the application migrates
// to addEventListener-based UI wiring.
Object.assign(globalThis, {
  KidSynth,
  addFriend,
  addSampleFriends,
  addStickerToCanvas,
  aliveMessages,
  animalReact,
  animationSpeed,
  celebrateName,
  clearCanvas,
  colors,
  cycleSpeechMessages,
  deleteDrawingFromGallery,
  deselectAllStickers,
  downloadDrawingPNG,
  draw,
  drawCanvasBackground,
  drawSpray,
  drawStar,
  filterStickers,
  filterTemplates,
  getFriends,
  getSavedDrawings,
  handleBackdropClick,
  handleWindowResize,
  initParticles,
  loadDrawingFromGallery,
  loadSuperhero,
  performFloodFill,
  placeStamp,
  positiveQuotes,
  redo,
  removeFriend,
  renderColors,
  renderFriendBadges,
  renderFriendList,
  renderGalleryGrid,
  renderHeroesGallery,
  renderMobileColors,
  renderStampsGallery,
  renderStickers,
  resetApp,
  resetFriends,
  resizeParticlesCanvas,
  restoreCanvas,
  saveCurrentDrawingToGallery,
  saveDrawing,
  saveDrawingToGallery,
  saveFriends,
  saveState,
  selectCanvasBg,
  selectColor,
  selectCustomColor,
  selectEraser,
  selectFillTool,
  selectSpray,
  selectStamp,
  setAnimationSpeed,
  setTemplateOpacity,
  setupCanvasDimensions,
  setupStickerPointerData,
  showEncouragement,
  spawnParticles,
  speakArabic,
  stampTemplates,
  startDrawing,
  state,
  stickersData,
  stopAllAnimations,
  stopDrawing,
  superheroes,
  synth,
  toggleFriendsModal,
  toggleGalleryModal,
  toggleGiveLife,
  toggleHelpModal,
  toggleHeroModal,
  toggleMirror,
  toggleMobileDrawer,
  toggleMusic,
  toggleSplitMode,
  toggleStampsModal,
  toggleTheme,
  triggerAnimation,
  triggerConfetti,
  undo,
  updateParticles,
  updateUndoRedoButtons,
});
