/* This file is generated by scripts/generate-entry.mjs. */
/* The application is now a real ES module graph; no source is concatenated here. */
import "../assets/css/base.css";
import "../assets/css/animations.css";
import "../assets/css/components.css";
import { initializeUI } from "../assets/js/ui.js";
import "../assets/js/lifecycle.js";

initializeUI();
